before_install:
  - sudo apt-get -y install jq
  # - wget `curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | .browser_download_url | select(endswith("deb"))'` -O pandoc.deb
  # - sudo dpkg -i pandoc.deb
  - sudo apt-get -y install pandoc
install:
  - python -m pip install --user ghp-import
before_script:
  - git config user.name "Travis-CI"
  - git config user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"
  - export PATH=$PATH:/home/travis/.cabal/bin
script:
  - make deploy
notifications:
  email: false
# whitelist
branches:
  only:
    - src
